### ISSUE TITLE
Sending Initial Server Response in Requested Language

### ISSUE THREAD

**Issue by daleee** [ngduc/react-setup#10]
Hey,

Firstly, thanks for putting this repo online! I learnt quite a bit from it when adding i18n and SSR to my own project.

I noticed that the original response being sent is in English no matter what the requested language is, and the requested language is only applied once the client-side starts to render.

Do you have any thoughts on how to send the initial response in the requested language? We get the locale & messages when the server gets an incoming request, but I haven't found a way to pass that data off to the main app container.

Edit: My bad, I didn't see that you mentioned working on this in #8.

**Comment by ngduc** [comment]
Hi,
Yes this is a known issue. I think locale is not injected properly on server side rendering. Will try to figure it out. If you could help that'd be great.

**Comment by ngduc** [comment]
@daleee Hi,
I've just committed a fix for this:
https://github.com/ngduc/react-setup/commit/b039dcdb6b56eec2e9e7672f2cee56498103e2a1

Could you let me know if that works?

**Comment by daleee** [comment]
@ngduc Hey, that worked! Thanks a lot! The lack of language flash looks great.

**Comment by daleee** [comment]
I've been thinking of a way to use a cookie to set the selected locale permanently without using the query string. The server would receive cookies attached with that domain, check if a locale has been set and respond appropriately. This is what I'm doing now:

```js
  // detect locale and get appropriate messages
  // order of checking:
  //  1) cookie
  //  2) query
  //  3) acceptsLanguages
  //  4) "en-US"
  let i18nObj = { locale: '', messages: {} };
  i18nObj.locale =
    (req.cookies && req.cookies.locale) ||
    (req.query && req.query.locale) ||
    (req.acceptsLanguages()[0]) ||
    'en-US';
```

One problem with this approach is that the `req` object is not available in the root component's `componentWillMount()` method. I've looked into ways of passing this data around. Doing something like what I have below technically works but I'm sure it would not scale very well with many requests coming in at once:

```js
// in server handler, after getting locale data
global["locale"] = i18nObj.locale;
```

```js
// in componentWillMount() of root component
  componentWillMount () {
    if (__CLIENT__) {
      ...
    }
    else {
      // server: grab locale data generated from request.
      // TODO: check cookie
      currentLocale = global["locale"] || this.props.location.query.locale || 'en-US';
      messages = translations[currentLocale];
    }

    ...
  }
```

Ideally, being able to pass the data directly using react-router's `match` method would be nice. Unfortunately, I don't think this is possible. I'll continue to investigate a possible solution for this.

**Comment by ngduc** [comment]
@daleee Using cookie is a better way than url query.
You should avoid using 'global' in node since it's applied for all requests (users).

The best way like you mentioned is to pass locale around using react-router so component can have it. I'm also looking into this, hopefully we will have a solution soon. Please keep me posted. Thanks.

**Comment by daleee** [comment]
Thanks to help from a kind fellow in the reactiflux react-router channel (natelaws!), I figured out a way to get everything working.

The problem is that `RouterContext` doesn't exactly let you pass props down to the components it wraps around. If I'm reading [the source for RouterContext](https://github.com/reactjs/react-router/blob/master/modules/RouterContext.js) correctly, only specific props are bundled into a `props` object and passed into the created component.

The way around this: using `context`. We can create a higher order component that wraps around RouterContext that doesn't do much other than adding our i18n data to the context:

```js
import React from 'react';
import { RouterContext } from 'react-router';

export default class HigherRouterContext extends React.Component {
  static childContextTypes = {
    intlData: React.PropTypes.object
  }

  getChildContext () {
    return { intlData: this.props.intlData };
  }

  constructor (props) {
    super(props);
  }

  render () {
    return <RouterContext { ...this.props } />;
  }
}
```

Then, in our server handler, we can pass the i18n object directly into the RouterContext which should pass it down the context chain:

```js
import React from 'react';
import { renderToString} from 'react-dom/server';
import { match, createMemoryHistory } from 'react-router';
import { Provider } from 'react-redux';

import routes from 'routes.jsx';

import configureStore from 'ducks/configureStore.js';
import initialView from 'helpers/initialView.js';
import fetchComponentData from 'helpers/fetchComponentData.js';
import { getLocaleMessages } from '../../tools/i18n.js';
import HigherRouterContext from 'components/common/HigherRouterContext.jsx';

const hostname = process.env.HOSTNAME || 'localhost';

export default (req, res) => {
  // create new store for this request
  const store = configureStore();
  // create new history
  const history = createMemoryHistory(req.url);

  // detect locale and get appropriate messages
  // order of checking:
  //  1) cookie
  //  2) query
  //  3) acceptsLanguages
  //  4) "en-US"
  let i18nObj = { locale: '', messages: {} };
  i18nObj.locale =
    (req.cookies && req.cookies.locale) ||
    (req.query && req.query.locale) ||
    (req.acceptsLanguages()[0]) ||
    'en-US';
  i18nObj.messages = getLocaleMessages(i18nObj.locale);

  match({ history, routes, location: req.url }, (err, redirect, props) => {
    if (err) {
      return res.status(500).send(err.message);
    }
    else if (redirect) {
      return res.redirect(redirect.pathname + redirect.search);
    }
    else if (!props) {
      return res.status(404).send('Not found.');
    }

    function renderPage () {
      const webserver = __DEV__ ? `//${hostname}:8080` : '';
      const component = (
        <Provider store={store}>
          <HigherRouterContext { ...props } intlData={i18nObj} />
        </Provider>
      );

      const componentHTML = renderToString(component);
      const initialState = store.getState();

      return initialView(componentHTML, initialState, i18nObj, webserver);
    }

    return fetchComponentData(store.dispatch, props.components, props.params)
                .then(renderPage)
                .then(html => res.send(html))
                .catch(err => res.send(err.message));

  });
}
```

Now that we have direct access to the i18n data on the server, we  don't need to get the translations yet again in our root component. In the `componentWillMount()` method, we can just do something like this:

```js
  componentWillMount () {
    if (__CLIENT__) {
      // client: grab locale data serialized from server & go with it.
      i18nObj = window.__LOCALE__;
      // technically this isn't necessary, since we did these checks on the server already
      currentLocale = i18nObj.locale ? i18nObj.locale : 'en-US'; 
      messages = i18nObj.messages ? i18nObj.messages : {};
    }
    else {
      // server: grab locale data generated from request & pushed into context
      const localeData = this.context.intlData;
      currentLocale = localeData.locale;
      messages = localeData.messages;
    }

    // add current locale
    addLocaleData({
      locale: currentLocale,
      parentLocale: currentLocale.split('-')[0]
    });
  }
```

With that, everything seems to work pretty smoothly!

Let me know if you have any questions or need a PR whipped up!

**Comment by ngduc** [comment]
Excellent! :100: 
Thanks for your help. Please create a PR (keep Transmit & no-semicolons :)

p/s: I noticed you use semicolons (it's fine), this may help you auto insert them: $ npm run lint -- --fix with eslint 'semi' rule enabled.

**Comment by ngduc** [comment]
Planning to create a wrapper around RouterContext to set context data & store locale like this:
https://github.com/reactjs/react-router/issues/1969

**Comment by ngduc** [comment]
This is done. Thanks @daleee
