### ISSUE TITLE
webpack run dev -- is error

### ISSUE THREAD

**Issue by kenny1har** [ngduc/react-setup#18]
> webpack run dev
is showing error:
webpack.validateSchema is not a function

**Comment by ngduc** [comment]
Hi, I've never used webpack run dev.
Try "npm run dev" to start the DEV mode.
Let me know if that works for you.

**Comment by kenny1har** [comment]
sorry,
npm run dev

webpack-dev-server#v2.1.0-beta.11
is causing error.

i changed:
"webpack-dev-server": "^2.1.0-beta"
to:
"webpack-dev-server": "2.1.0-beta.10"

**Comment by ngduc** [comment]
Right, I've just found out that too & pushed a commit to use 2.1.0-beta.9, will update it to .10 later.
Thanks

**Comment by ngduc** [comment]
https://github.com/ngduc/react-setup/commit/5b0f2657d8adb75afa31b938ac5c2b83a6ca7ebe

**Comment by ngduc** [comment]
http://stackoverflow.com/questions/40597626/webpack-validateschema-is-not-a-function
