### ISSUE TITLE
client.js is not found

### ISSUE THREAD

**Issue by kenny1har** [ngduc/react-setup#19]
npm run dev
is loading a 404 error client.js

different path for client.js

in the dev mode, client.js is located at /static/client.js
in the production mode, the path become incorrect. /client.js

renderAppRouter.js

production
```
const output = Transmit.injectIntoMarkup(
  renderedHtml, reactData, [`${webserver}/client.js?${webpackHash}`]
)
```

dev
```
const output = Transmit.injectIntoMarkup(
  renderedHtml, reactData, [`${webserver}/static/client.js?${webpackHash}`]
)
```

**Comment by ngduc** [comment]
"in the dev mode, client.js is located at /static/client.js" => not correct.
In DEV mode, it's loading /client.js from webpack server, for example: http://localhost:8199/client.js

in PROD mode, it's loading /client.js normally.
I've just tried it works for me in both modes. Is it broken for you?

**Comment by ngduc** [comment]
![image](https://cloud.githubusercontent.com/assets/639189/20418369/a4cd51dc-ad01-11e6-858b-1fefdfab58bd.png)

**Comment by kenny1har** [comment]
![client](https://cloud.githubusercontent.com/assets/1797207/20418491/c547f6ba-ad88-11e6-93ab-ddb966818cdf.PNG)
i did a clean clone from github.
npm run dev

*windows 10

**Comment by ngduc** [comment]
Your path looks correct. I'm using a Mac. It works on multiple projects of mine.
It could be something wrong with Webpack. If you find a solution, please let me know.

**Comment by kenny1har** [comment]
before:
![before](https://cloud.githubusercontent.com/assets/1797207/20418814/342f2fe6-ad8c-11e6-862c-6421dca7b3e1.PNG)

after:
![after](https://cloud.githubusercontent.com/assets/1797207/20418835/4b3e6666-ad8c-11e6-8236-3a632ad7a4fd.PNG)
