### ISSUE TITLE
Checksum problems

### ISSUE THREAD

**Issue by prewk** [ngduc/react-setup#8]
It seems to be server-rendering in English and then client rendering in Japanese with the `?locale=ja-JP` param. This causes a console error.

**Comment by ngduc** [comment]
Production build does not have that error. (npm run build && npm start)
Server still renders Eng version first, then apply JP strings right away (it flickers a few ms). I'm trying to make it render with locale strings completely.

**Comment by ngduc** [comment]
@prewk Hi,
I've just committed a fix for this:
https://github.com/ngduc/react-setup/commit/b039dcdb6b56eec2e9e7672f2cee56498103e2a1

Could you let me know if that works?

**Comment by ngduc** [comment]
Fixed in https://github.com/ngduc/react-setup/issues/10

**Comment by prewk** [comment]
Confirmed!

`react-intl` is complaining about having to use fallbacks in English:

````js
````

**Comment by ngduc** [comment]
I think they'll fix it soon, or we have to patch console.log:
https://github.com/yahoo/react-intl/issues/251

**Comment by prewk** [comment]
That's good news. I use it in another project and I hate those errors.

**Comment by ngduc** [comment]
This is fixed by setting defaultLocale which I've just committed.
